### ISSUE TITLE
Crash - java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/asr_trial.txt"

### ISSUE THREAD

**Issue by manimaran96** [manimaran96/Spell4Wiki#55]
**Describe the bug**
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=42, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/asr_trial.txt flg=0x43 }} to activity {com.manimarank.spell4wiki/com.manimarank.spell4wiki.ui.spell4wiktionary.Spell4WordListActivity}: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/asr_trial.txt"
at android.app.ActivityThread.deliverResults(ActivityThread.java:4546)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4588)

**Basic information**
DATE & TIME : 01-11-2022 07:10:53 AM
APP.VERSION : 1.2.3_13
TIMEZONE : Africa/Accra
VERSION.RELEASE : 9 & SDK : 28
BRAND & MODEL : lge & LGM-G600K
DEVICE : lucye
CPU_ABI : arm64-v8a

**Comment by manimaran96** [comment]
Sorry for the crash 🙏. The issue causing java.lang.RuntimeException has been fixed in the latest update 🚀. Please update Spell4Wiki and share your feedback — it helps us improve 💙.
