### ISSUE TITLE
Crash - java.lang.NullPointerException Spell4WordListActivity

### ISSUE THREAD

**Issue by manimaran96** [manimaran96/Spell4Wiki#57]
**Describe the bug**
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=42, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/document:24424 flg=0x43 }} to activity {com.manimarank.spell4wiki/com.manimarank.spell4wiki.ui.spell4wiktionary.Spell4WordListActivity}: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
at com.manimarank.spell4wiki.utils.RealPathUtil.getDataColumn(RealPathUtil.kt:138)
at com.manimarank.spell4wiki.utils.RealPathUtil.getRealPathFromURI_API19(RealPathUtil.kt:104)
at com.manimarank.spell4wiki.utils.RealPathUtil.getRealPath(RealPathUtil.kt:26)
at com.manimarank.spell4wiki.ui.spell4wiktionary.Spell4WordListActivity.onActivityResult(Spell4WordListActivity.kt:130)

**Basic information**
DATE & TIME : 02-08-2022 05:27:28 பிற்பகல்
APP.VERSION : 1.2.3_13
TIMEZONE : Asia/Kolkata
VERSION.RELEASE : 11 & SDK : 30
BRAND & MODEL : Redmi & M2003J15SC
DEVICE : merlin
CPU_ABI : arm64-v8a

**Comment by manimaran96** [comment]
Fixed
